services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${OBSERVE_DB_DATABASE}
      POSTGRES_USER: ${OBSERVE_DB_USERNAME}
      POSTGRES_PASSWORD: ${OBSERVE_DB_PASSWORD}
    ports:
      - "${OBSERVE_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: t.hc199811@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${OBSERVE_DB_PASSWORD}
      POSTGRES_DB: ${OBSERVE_DB_DATABASE}
      POSTGRES_USER: ${OBSERVE_DB_USERNAME}
      POSTGRES_PASSWORD: ${OBSERVE_DB_PASSWORD}
      PGADMIN_LISTEN_PORT: 3000
    ports:
      - "5000:3000"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp:
